language: cpp
matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-4.9
      addons: {apt: {packages: [g++-4.9], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: COMPILER=g++-5
      addons: {apt: {packages: [g++-5], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: COMPILER=g++-6
      addons: {apt: {packages: [g++-6], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: COMPILER=g++-7
      addons: {apt: {packages: [g++-7], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: COMPILER=g++-8
      addons: {apt: {packages: [g++-8], sources: [ubuntu-toolchain-r-test]}}
    - compiler: gcc
      env: COMPILER=g++-9
      addons: {apt: {packages: [g++-9], sources: [ubuntu-toolchain-r-test]}}
    - compiler: clang
      env: COMPILER=clang++
    - os: osx
      env: COMPILER=clang++
script:
  - CXX=$COMPILER C_FLAGS=-Werror make -k -C src full
  - CXX=$COMPILER C_FLAGS=-Werror make -k -C tests udpipe_bundle
  - perl tests/ascii_only.pl
